#!/usr/bin/env python3
"""Reproduce the manuscript's three-domain adjusted-prediction Figure 1.

Input is `three_domain_adjusted_predictions.csv`, generated by the complete
HRS analysis pipeline. The CSV contains Model 3 marginal predictions and
HC3-based 95% confidence limits for each contact-transition group.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd


DOMAIN_SPECS = {
    "friends": {"label": "Friends"},
    "other_relatives": {"label": "Other relatives"},
    "children": {"label": "Children"},
}

CONTACT_ORDER = [
    "maintained_frequent",
    "increased_contact",
    "decreased_contact",
    "maintained_infrequent",
]

CONTACT_LABELS = {
    "maintained_frequent": "Maintained frequent",
    "increased_contact": "Increased contact",
    "decreased_contact": "Decreased contact",
    "maintained_infrequent": "Maintained infrequent",
}

CONTACT_COLORS = {
    "maintained_frequent": "#0072B2",
    "increased_contact": "#009E73",
    "decreased_contact": "#D55E00",
    "maintained_infrequent": "#CC79A7",
}


def plot_predictions(predictions: pd.DataFrame, output_dir: Path) -> None:
    """Create the exact combined Figure 1 used in the manuscript."""
    global_low = float(predictions["ci_95_low"].min())
    global_high = float(predictions["ci_95_high"].max())
    margin = 0.05 * (global_high - global_low)
    y_limits = (global_low - margin, global_high + margin)

    def draw_panel(ax: plt.Axes, domain: str) -> None:
        domain_data = predictions.loc[predictions["domain"].eq(domain)]
        for group in CONTACT_ORDER:
            part = domain_data.loc[
                domain_data["contact_group"].eq(group)
            ].sort_values("delta_loneliness")
            ax.plot(
                part["delta_loneliness"],
                part["adjusted_prediction"],
                color=CONTACT_COLORS[group],
                linewidth=2.2,
                label=CONTACT_LABELS[group],
            )
            ax.fill_between(
                part["delta_loneliness"].to_numpy(float),
                part["ci_95_low"].to_numpy(float),
                part["ci_95_high"].to_numpy(float),
                color=CONTACT_COLORS[group],
                alpha=0.14,
                linewidth=0,
            )
        ax.axvline(0, color="#555555", linestyle="--", linewidth=1.2)
        ax.set_title(DOMAIN_SPECS[domain]["label"], fontsize=13, weight="bold")
        ax.set_xlim(-1, 1)
        ax.set_ylim(*y_limits)
        ax.grid(axis="both", color="#E6E6E6", linewidth=0.8)
        ax.spines[["top", "right"]].set_visible(False)

    plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 10})
    fig, axes = plt.subplots(
        1, 3, figsize=(15.5, 5.4), sharex=True, sharey=True
    )
    for index, domain in enumerate(DOMAIN_SPECS):
        draw_panel(axes[index], domain)

    axes[0].set_ylabel("Adjusted predicted cognition at T3")
    fig.supxlabel("Change in UCLA-3 loneliness (T2 - T1)", y=0.07)
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(
        handles,
        labels,
        loc="lower center",
        ncol=4,
        frameon=False,
        fontsize=9,
        bbox_to_anchor=(0.5, -0.005),
    )
    fig.suptitle(
        "Contact transition and subsequent cognition",
        fontsize=16,
        weight="bold",
        y=0.99,
    )
    fig.tight_layout(rect=[0.02, 0.11, 1.0, 0.95])

    output_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(
        output_dir / "three_domain_interaction_figure.png",
        dpi=300,
        bbox_inches="tight",
    )
    fig.savefig(
        output_dir / "three_domain_interaction_figure.pdf",
        bbox_inches="tight",
    )
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--predictions",
        type=Path,
        required=True,
        help="Path to three_domain_adjusted_predictions.csv",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory for the PNG and PDF figures",
    )
    args = parser.parse_args()

    predictions = pd.read_csv(args.predictions)
    required = {
        "domain",
        "contact_group",
        "delta_loneliness",
        "adjusted_prediction",
        "ci_95_low",
        "ci_95_high",
    }
    missing = sorted(required.difference(predictions.columns))
    if missing:
        raise ValueError(f"Prediction file is missing columns: {missing}")

    plot_predictions(predictions, args.output_dir)


if __name__ == "__main__":
    main()
